openapi: 3.0.0
info:
  title: Usuarios
  version: 0.0.1
servers:
  - url: http://localhost:3000/v1
    description: Entorno Desarrollo
  - url: https://produccion.com/v1
    description: Servidor de produccion
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
  
paths:
  /users:
    get:
      summary: Retorna listado de usuario.
      responses:
        '200':    # status code
          description: Un array de usuarios
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Crear un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
      responses: 
        '201':
          description: Created
  /users/{username}:
    delete:
      summary: Elimina un usuario
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: Nombre de usuario
      
      responses: 
        '200':
          description: El usuario ha sido eliminado
        '409':
          description: El usuario no ha sido eliminado
  /demo:
    get:
      summary: Retorna listado de usuario.
      security:
        - bearerAuth: []
      responses:
        '200':    # status code
          description: Un array de usuarios
        '401':    # status code
          description: Usuario no autorizado  
          
  /login:
    post:
      summary: Retorna un token para utilizar en el endpoint demo
      responses:
        '200':    # status code
          description: Token válido
        '401':    # status code
          description: Usuario no autorizado
          